// Loading and connect screen captions.
//
// cg_info.c and ui_connect.c register these by bare name, so each needs a
// shader to point at its image; the images themselves are generated by
// Tools/dev/make_ui_art.py. Both screens draw over the map's levelshot, hence
// alpha blending and no mipmaps.

loading
{
	nopicmip
	nomipmaps
	{
		map interface/art/loading.png
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

ready
{
	nopicmip
	nomipmaps
	{
		map interface/art/ready.png
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

connecting
{
	nopicmip
	nomipmaps
	{
		map interface/art/connecting.png
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

searching
{
	nopicmip
	nomipmaps
	{
		map interface/art/searching.png
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}

dots
{
	nopicmip
	nomipmaps
	{
		map interface/art/dots.png
		blendfunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
	}
}
