#!/usr/bin/env bash
# Sweep the aura's tuning and capture what each setting actually looks like.
#
# The aura is described entirely by numbers in the tier config - amplitude,
# wavelength, scroll speed, scale, padding, colour - and none of them mean
# anything until you see the result. Iterating by hand costs a launch, a spawn,
# holding the powerup key and a screenshot, per value.
#
# This renders in the engine rather than approximating the shader elsewhere. The
# shape comes out of glsl/aura_vp.glsl against the player's real screen-space
# bounding box, so what you get back is the aura, not a drawing of one. The cost
# is a game launch per sample, which is why it batches.
#
# Nothing has to be pressed because auraAlways makes the aura draw on its own
# (cg_players.c:2101); the script sets it for the duration and restores the
# config afterwards.
#
# usage:
#   zeq2aura.sh --sweep auraAmplitude=0.5,1,2,4
#   zeq2aura.sh --sweep auraScrollSpeed=0,1.5,4 --set auraAmplitude=2
#   zeq2aura.sh --set auraColor="1 0.2 0.2" --out /tmp/red.png
#   zeq2aura.sh --set auraColor="1 0 0" --hull        # stock old aura, for A/B
#   zeq2aura.sh --sweep auraScale=1,2,3 --crop none      # keep whole frames
#   zeq2aura.sh --sweep auraScale=1,2,3 --range 160      # pull the camera back
#
# Writes a labelled contact sheet, one cell per sample.

source "$(dirname "${BASH_SOURCE[0]}")/zeq2env.sh"

MAP=desert
OUT="$ZEQ2_BUILD/aura-sweep.png"
SWEEP=""
FIXED=()
FRAMES=400
CROP=470x640
RANGE=110
HULL=0
KEEP=0

# Keys the hull path does not read at all - passing them to it does nothing.
SS_ONLY="auraOriginDistance auraPadding auraAmplitude auraWavelength auraScrollSpeed"

# Read by both, but tuned for the screen-space path, which wants it several
# times larger than the hull path ever did. Overriding it under --hull is what
# actually distorts the comparison.
SS_SHARED="auraScale"

while [[ $# -gt 0 ]]; do
	case "$1" in
		--sweep)   SWEEP="$2"; shift 2 ;;
		--set)     FIXED+=("$2"); shift 2 ;;
		--map)     MAP="$2"; shift 2 ;;
		--out)     OUT="$2"; shift 2 ;;
		--frames)  FRAMES="$2"; shift 2 ;;
		--crop)    CROP="$2"; shift 2 ;;
		--range)   RANGE="$2"; shift 2 ;;
		--hull)    HULL=1; shift ;;
		--keep)    KEEP=1; shift ;;
		-h|--help) sed -n '2,26p' "${BASH_SOURCE[0]}"; exit 0 ;;
		*) echo "unknown option: $1" >&2; exit 2 ;;
	esac
done

zeq2_require_bin

TIER="$ZEQ2_BUILD/$ZEQ2_GAME/players/tierDefault.cfg"

# --hull renders the old convex-hull aura, and the only reason to do that is to
# A/B it against the new one. That comparison is worthless if the old path is
# fed the new path's numbers.
#
# The two share auraColor and auraScale but nothing else. auraScale is the one
# that does damage: both paths read it, and the screen-space path wants it
# several times larger than the hull path ever did, so carrying it across
# inflates the old aura into something it never looked like. The other five
# keys the hull path never reads, so passing them is a no-op - but a silent one,
# which is worse, because the run looks like it compared them.
#
# So --hull starts from the committed tierDefault.cfg rather than the staged
# one, and drops any --set or --sweep on a screen-space key. auraColor still
# passes through, because comparing the two paths at the same colour is the
# whole point. Say so out loud: silently discarding what was asked for is worse
# than the distortion it prevents.
STOCK=""
if [[ $HULL -eq 1 ]]; then
	if STOCK="$(git -C "$ZEQ2_ROOT" show HEAD:GameData/players/tierDefault.cfg 2>/dev/null)" \
	   && [[ -n "$STOCK" ]]; then
		echo "hull: rendering the committed aura config, not the tuned one"
	else
		STOCK=""
		echo "hull: warning - no committed tierDefault.cfg to fall back on;" \
		     "using the staged one, which carries the screen-space tuning" >&2
	fi
fi
[[ -f "$TIER" ]] || { echo "error: $TIER not found - run zeq2build.sh first" >&2; exit 1; }

# The config is staged from GameData by every build, so a crash mid-sweep costs
# nothing permanent - but restore it anyway so an interrupted run does not leave
# auraAlways on.
BACKUP="$(mktemp)"
cp "$TIER" "$BACKUP"
cleanup() { cp "$BACKUP" "$TIER"; rm -f "$BACKUP"; }
trap cleanup EXIT INT TERM

# Replace `key value` in the tier config, appending if the key is absent.
# The player configs ship with CRLF, and both branches below used to write LF:
# awk's `print` emits a bare newline, so a rewritten key lost its carriage
# return while every untouched line kept one, and an appended key added an LF
# line to a CRLF file. Either way the file ends up with mixed endings, and the
# next diff against stock assets reports every line as changed - which buries
# the handful of lines that really did.
#
# So detect what the file already uses and match it. Nothing here can assume
# CRLF outright: the configs under GameData are CRLF, but a file generated by
# these scripts is not.
set_key() {
	local key="$1" value="$2" file="$3"
	local eol=""
	# A carriage return before the first newline means the file is CRLF.
	if head -c 4096 "$file" | grep -q $'\r'; then
		eol=$'\r'
	fi
	if grep -qE "^[[:space:]]*$key[[:space:]]" "$file"; then
		local tmp; tmp="$(mktemp)"
		awk -v k="$key" -v v="$value" -v eol="$eol" '
			$1 == k { printf "%s %s%s\n", k, v, eol; next } { print }
		' "$file" > "$tmp" && mv "$tmp" "$file"
	else
		printf '%s %s%s\n' "$key" "$value" "$eol" >> "$file"
	fi
}

if [[ -z "$SWEEP" ]]; then
	SWEEP_KEY="sample"
	SWEEP_VALUES=("only")
else
	SWEEP_KEY="${SWEEP%%=*}"
	IFS=',' read -r -a SWEEP_VALUES <<< "${SWEEP#*=}"
	[[ ${#SWEEP_VALUES[@]} -gt 0 ]] || { echo "error: --sweep has no values" >&2; exit 2; }
fi

WORK="$(mktemp -d)"
[[ $KEEP -eq 1 ]] || trap 'cleanup; rm -rf "$WORK"' EXIT INT TERM

echo "=== aura sweep: $SWEEP_KEY over ${#SWEEP_VALUES[@]} value(s), map $MAP ==="

shots=()
for value in "${SWEEP_VALUES[@]}"; do
	if [[ -n "$STOCK" ]]; then
		printf '%s\n' "$STOCK" > "$TIER"
	else
		cp "$BACKUP" "$TIER"
	fi
	set_key auraExists  True "$TIER"
	set_key auraAlways  True "$TIER"
	for kv in "${FIXED[@]}"; do
		key="${kv%%=*}"
		if [[ $HULL -eq 1 && " $SS_ONLY " == *" $key "* ]]; then
			echo "  (hull: ignoring $key - the hull path never reads it)" >&2
			continue
		fi
		if [[ $HULL -eq 1 && " $SS_SHARED " == *" $key "* ]]; then
			echo "  (hull: ignoring $key - read by both, but this value is" \
			     "tuned for the screen-space path)" >&2
			continue
		fi
		set_key "$key" "${kv#*=}" "$TIER"
	done
	if [[ "$SWEEP_KEY" != "sample" ]]; then
		if [[ $HULL -eq 1 && " $SS_ONLY $SS_SHARED " == *" $SWEEP_KEY "* ]]; then
			echo "  (hull: ignoring swept $SWEEP_KEY - see --hull notes)" >&2
		else
			set_key "$SWEEP_KEY" "$value" "$TIER"
		fi
	fi

	label="$SWEEP_KEY $value"
	safe="$(printf '%s' "$SWEEP_KEY-$value" | tr -c 'A-Za-z0-9._-' '-')"
	shot="$WORK/$safe.png"
	printf '  %-28s ' "$label"

	# Fixed camera and no HUD, so the only thing differing between cells is the
	# aura. The spawn point still varies, so the backdrop does too - that is
	# scenery, not the subject.
	#
	# The camera cvars are passed as bare commands rather than `+set`: they are
	# CVAR_ARCHIVE and sit in zeq2config.cfg, whose exec would overwrite an early
	# `+set`. A command goes into the buffer and runs after that. cg_thirdPersonSlide
	# defaults to -20, which is what pushes the player off to one side.
	if "$ZEQ2_DEV/zeq2shot.sh" --map "$MAP" --frames "$FRAMES" --out "$shot" \
		-- +set cg_auraScreenSpace $(( HULL ? 0 : 1 )) +set cg_draw2D 0 \
		   +cg_thirdPersonSlide 0 +cg_thirdPersonHeight 0 \
		   +cg_thirdPersonAngle 0 +cg_thirdPersonRange "$RANGE" >/dev/null 2>&1 && [[ -f "$shot" ]]; then
		echo "ok"
		shots+=("$shot")
	else
		echo "FAILED (no screenshot)"
	fi
done

if [[ ${#shots[@]} -eq 0 ]]; then
	echo "error: every sample failed - try one by hand with zeq2shot.sh" >&2
	exit 1
fi

cols=2
[[ ${#shots[@]} -eq 1 ]] && cols=1
crop_arg=()
[[ -n "$CROP" && "$CROP" != "none" ]] && crop_arg=(--crop "$CROP")
python3 "$ZEQ2_DEV/png_sheet.py" "$OUT" "${shots[@]}" --columns "$cols" --label --pad 6 "${crop_arg[@]}"

[[ $KEEP -eq 1 ]] && echo "individual frames kept in $WORK"
echo "renderer: $([[ $HULL -eq 1 ]] && echo 'convex hull (cg_auraScreenSpace 0)' || echo 'screen space (cg_auraScreenSpace 1)')"
