#!/usr/bin/env python3
"""Generate PNG fixtures for tests/suites/test_png.c.

    python3 tests/fixtures/gen_png.py     # rewrites png_fixtures.h in place

Fixtures are embedded as byte arrays rather than shipped as files so the PNG
suite needs no game assets and makes no assumption about the working directory.

Coverage rationale: a single truecolour-alpha image leaves most of the decoder
untested. The loader branches hard on ColourType (grey / truecolour / indexed),
on bit depth (4-bit indexed packs two pixels per byte), and on the presence of a
tRNS chunk - and each of those paths does its own pointer walking over the file
buffer. The malformed fixtures at the end exist because the tRNS length
validation in tr_image_png.c was dead code, so a wrong-length chunk was accepted
and then read as if it were the right length.
"""

import os
import struct
import zlib

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "png_fixtures.h")

GREY, TRUE, INDEXED, GREY_ALPHA, RGBA = 0, 2, 3, 4, 6


def chunk(tag, data):
    return (struct.pack(">I", len(data)) + tag + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))


def build(width, height, depth, colour_type, scanlines, palette=None, trns=None):
    """scanlines: list of bytes objects, WITHOUT the per-row filter byte."""
    raw = b"".join(b"\x00" + row for row in scanlines)
    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, depth,
                                      colour_type, 0, 0, 0))
    if palette is not None:
        png += chunk(b"PLTE", palette)
    if trns is not None:
        png += chunk(b"tRNS", trns)
    png += chunk(b"IDAT", zlib.compress(raw, 9))
    png += chunk(b"IEND", b"")
    return png


def carray(name, data, per_line=12):
    lines = []
    for i in range(0, len(data), per_line):
        lines.append("\t" + ", ".join("0x%02x" % b for b in data[i:i + per_line]) + ",")
    return "static const unsigned char %s[] = {\n%s\n};\n" % (name, "\n".join(lines))


def main():
    out = ['''/*
GENERATED by tests/fixtures/gen_png.py - do not edit by hand.

PNG fixtures for tests/suites/test_png.c. Each valid image exercises a different
decoder path; the malformed ones at the end must be rejected.
*/

#ifndef PNG_FIXTURES_H
#define PNG_FIXTURES_H
''']

    # --- truecolour + alpha, the original fixture -------------------------------
    px = [(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 128), (16, 32, 48, 64)]
    rows = [bytes(px[0]) + bytes(px[1]), bytes(px[2]) + bytes(px[3])]
    out.append("/* 2x2 8-bit RGBA. Chunk headers land at odd offsets: signature 8 +\n"
               "   (4+4+13+4) puts the next header at byte 33, which is what made the\n"
               "   loader's pointer-cast reads misaligned. */\n")
    out.append("#define PNG_2X2_WIDTH  2\n#define PNG_2X2_HEIGHT 2\n")
    out.append(carray("png_2x2_rgba", build(2, 2, 8, RGBA, rows)))
    out.append(carray("png_2x2_expected", b"".join(bytes(p) for p in px)))

    # --- greyscale + tRNS ------------------------------------------------------
    # Grey levels; 0x40 is declared fully transparent by the tRNS chunk.
    grey = [0x00, 0x40, 0x80, 0xFF]
    rows = [bytes(grey[0:2]), bytes(grey[2:4])]
    out.append("\n/* 2x2 8-bit greyscale with a 2-byte tRNS naming 0x40 transparent. */\n")
    out.append(carray("png_grey_trns", build(2, 2, 8, GREY, rows,
                                            trns=struct.pack(">H", 0x40))))

    # --- truecolour + tRNS -----------------------------------------------------
    rgb = [(10, 20, 30), (200, 100, 50), (0, 0, 0), (255, 255, 255)]
    rows = [bytes(rgb[0]) + bytes(rgb[1]), bytes(rgb[2]) + bytes(rgb[3])]
    out.append("\n/* 2x2 8-bit truecolour with a 6-byte tRNS naming (0,0,0) transparent. */\n")
    out.append(carray("png_true_trns", build(2, 2, 8, TRUE, rows,
                                            trns=struct.pack(">HHH", 0, 0, 0))))

    # --- indexed 8-bit + PLTE + tRNS -------------------------------------------
    pal = bytes([255, 0, 0,  0, 255, 0,  0, 0, 255,  255, 255, 0])
    rows = [bytes([0, 1, 2]), bytes([3, 2, 1])]
    out.append("\n/* 3x2 8-bit indexed, 4-entry palette, tRNS alpha table. */\n")
    out.append(carray("png_indexed8_plte_trns",
                      build(3, 2, 8, INDEXED, rows, palette=pal,
                            trns=bytes([0xFF, 0x80, 0x00, 0x40]))))

    # --- indexed 4-bit + PLTE (two pixels per byte, no tRNS) -------------------
    rows = [bytes([0x01, 0x23]), bytes([0x32, 0x10])]
    out.append("\n/* 4x2 4-bit indexed: two pixels packed per byte, no tRNS. */\n")
    out.append(carray("png_indexed4_plte",
                      build(4, 2, 4, INDEXED, rows, palette=pal)))

    # --- malformed: tRNS length wrong for the colour type ----------------------
    # tr_image_png.c validated these with `if(!ChunkHeaderLength == 2)`, which
    # parses as `(!ChunkHeaderLength) == 2` and is therefore always false. The
    # chunk was accepted and the truecolour branch then read Trans[0..5] from a
    # 2-byte buffer.
    rgb_rows = [bytes(rgb[0]) + bytes(rgb[1]), bytes(rgb[2]) + bytes(rgb[3])]
    out.append("\n/* MALFORMED: truecolour tRNS must be 6 bytes; this one is 2. */\n")
    out.append(carray("png_bad_trns_true",
                      build(2, 2, 8, TRUE, rgb_rows, trns=b"\x00\x00")))

    grey_rows = [bytes(grey[0:2]), bytes(grey[2:4])]
    out.append("\n/* MALFORMED: greyscale tRNS must be 2 bytes; this one is 4. */\n")
    out.append(carray("png_bad_trns_grey",
                      build(2, 2, 8, GREY, grey_rows, trns=b"\x00\x40\x00\x00")))

    out.append("\n#endif\n")

    with open(OUT, "w") as fh:
        fh.write("".join(out))
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
